vim_plugin_task "bufexplorer",      "http://www.vim.org/scripts/download_script.php?src_id=14208"
vim_plugin_task "specky",           "git://github.com/vim-scripts/Specky.git"
vim_plugin_task "matchit",          "http://www.vim.org/scripts/download_script.php?src_id=8196"
vim_plugin_task "textobj-user",     "git://github.com/kana/vim-textobj-user.git"
vim_plugin_task "textobj-rubyblock","git://github.com/nelstrom/vim-textobj-rubyblock.git"
vim_plugin_task "ruby-refactoring", "git://github.com/ecomba/vim-ruby-refactoring.git"
vim_plugin_task "zen-coding",       "git://github.com/mattn/zencoding-vim.git"
vim_plugin_task "bundler",          "git://github.com/tpope/vim-bundler.git"
vim_plugin_task "vim-blockle",      "git://github.com/jgdavey/vim-blockle.git"
vim_plugin_task "delimitMate",      "git://github.com/Raimondi/delimitMate.git"
vim_plugin_task "vim-markdown-preview", "git://github.com/henrik/vim-markdown-preview.git"
